App/models.py


from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()





class User(db.Model):
    '''User模型'''
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)
    gender = db.Column(db.Enum('male', 'female', 'unknown'), default='unknown')
    birthday = db.Column(db.Date, default='1990-01-01')
    location = db.Column(db.String(10), nullable=False)
    bio = db.Column(db.String(256), default='')
    created = db.Column(db.DateTime)  # 用户注册时间
    avatar = db.Column(db.String(128), default='/static/img/default.jpg')


class Weibo(db.Model):
    '''微博表'''
    __tablename__ = 'weibo'

    id = db.Column(db.Integer, primary_key=True)
    uid = db.Column(db.Integer, nullable=False)
    content = db.Column(db.Text, nullable=False)
    created = db.Column(db.DateTime, nullable=False)
    updated = db.Column(db.DateTime, nullable=False)

    @property
    def user(self):
        if not hasattr(self, '_user'):
            self._user = User.query.get(self.uid)
        return self._user


App/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_session import Session

from App.models import db


def create_app():
    app = Flask(__name__)

    # session
    app.config['SECRET_KEY'] = '110'
    app.config['SESSION_TYPE'] = 'redis'
    Session(app=app)

    # sqlalchemy
    # dialect+driver://root:password@host:port/database
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:Ccc!950607@49.235.21.234:3306/lianxi3'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    db.init_app(app=app)

    # migrate
    migrate = Migrate()
    migrate.init_app(app=app, db=db)
    return app

App/views.py
import datetime

from flask import Blueprint, request, redirect, url_for, render_template, session
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import exc

from App.models import User, db, Weibo
from App.utils import make_password, check_password, save_avatar, login_required

blue = Blueprint('blue', __name__)


@blue.route('/')
def hello_world():
    return 'Hello World!'


@blue.route('/register/',methods=('GET','POST'))
def register():
    if request.method == 'POST':
        username = request.form.get('username','').strip()
        password = request.form.get('password','').strip()
        gender = request.form.get('gender')
        birthday = request.form.get('birthday')
        location = request.form.get('location','').strip()
        bio = request.form.get('bio')

        if username == '' or password == '':
            return render_template('register.html',error='昵称和密码不能为空')
        safe_password = make_password(password)

        user = User(username=username, password=password, gender=gender,
                    birthday=birthday, location=location, bio=bio, created=datetime.datetime.now())

        db.session.add(user)
        try:
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
            return render_template('register.html', err="昵称已存在，请换一个")
        else:
            return redirect(url_for('blue.login'))
    else:
        return render_template('register.html')


@blue.route('/login/', methods=('GET', 'POST'))
def login():

    if request.method == 'POST':

        username = request.form.get('username','').strip()
        password = request.form.get('password','').strip()


        try:
            user = User.query.filter_by(username=username, password=password).one()
        except exc.NoResultFound:
            return render_template('login.html', err='用户名密码错误')

        if check_password(password, user.password):

            session['uid'] = user.id
            session['username'] = user.username

            return redirect(url_for('blue.info'))
        else:
            return render_template('login.html', err='用户名或密码错误')

    else:
        return render_template('login.html')


@blue.route('/info/')
def info():
    if 'uid' in session:
        uid = session['uid']
        user = User.query.get(uid)
        return render_template('info.html', user=user)
    else:
        return redirect(url_for('blue.login'))


@blue.route('/logout/')
def logout():
    session.pop('uid')
    session.pop('username')
    return redirect(url_for('blue.login'))


@blue.route('/update/')
@login_required
def update():
    uid = session['uid']
    user = User.query.get(uid)

    if request.method == 'POST':
        username = request.form.get('username', '').strip()
        gender = request.form.get('gender')
        birthday = request.form.get('birthday')
        location = request.form.get('location', '').strip()
        bio = request.form.get('bio', '').strip()
        avatar = request.files.get('avatar')

        if username == '':
            return render_template('update.html', err="昵称不允许为空！")

        user.username = username
        user.gender = gender
        user.birthday = birthday
        user.location = location
        user.bio = bio

        # 检查并保存用户头像
        if avatar:
            avatar_url = save_avatar(uid, avatar)
            user.avatar = avatar_url

        try:
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
            return render_template('update.html', err="昵称已存在，请换一个", user=user)
        else:
            session['username'] = username
            return redirect('/user/info')
    else:

        return render_template('update.html', user=user)

@blue.route('/sendWeibo/',methods=('GET', 'POST'))
def sendWeibo():
    if 'uid' not in session:
        return redirect(url_for('blue.login'))

    if request.method == 'POST':
        uid = session['uid']
        title = request.form.get('title')
        content = request.form.get('content')
        created = datetime.datetime.now()
        weibo = Weibo(uid=uid,title=title,content=content,created=created)

        db.session.add(weibo)
        db.session.commit()

        return redirect(url_for('blue.show_weibo'))
    else:
        return render_template('sendWeibo.html')


@blue.route('/show_weibo/')
def show_weibo():
    all_weibo = Weibo.query.all()
    return render_template('show_weibo.html',all_weibo=all_weibo)



App/templates/base.html
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="/static/css/bootstrap.min.css">

        <title>迷你微博</title>

        <style>
            body { margin: 0 auto; padding: 0; }

            h1 { margin: 30px 0; }

            .footbar {
                padding: 30px 0;
                font-size: 0.6em;
                color: gray;
                text-align: center;
            }
        </style>
    </head>

    <body>
        <!-- 导航栏 -->
        <nav class="navbar navbar-expand navbar-dark bg-dark">
            <a class="navbar-brand" href="/">
              <img src="/static/img/logo.png" width="30" class="d-inline-block align-top" alt="" loading="lazy">
              迷你微博
            </a>

            <div class="collapse navbar-collapse justify-content-between">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">关注的人</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">粉丝列表</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">热门微博</a>
                    </li>
                </ul>

                <ul class="navbar-nav">
                    {% if 'uid' in session %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blue.info') }}">{{ session.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blue.post') }}">发微博</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blue.logout') }}">退出</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blue.register') }}">注册</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blue.login') }}">登录</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <!-- 内容容器 -->
        <div class="container">
            <div class="row">
                <!-- 内容区 -->
                <div class="col-sm-8">
                    {% block content %}{% endblock %}
                </div>

                <!-- 边栏 -->
                <div class="col-sm-4">
                    {% block sidebar %}{% endblock %}
                </div>
            </div>
        </div>

        <!-- 底栏 -->
        <div class="footbar">
            版权所有 @ 新浪
        </div>

        <!-- JS -->
        <script src="/static/js/jquery-3.5.1.slim.min.js"></script>
        <script src="/static/js/popper.min.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
    </body>
</html>

App/templates/info.html
{% extends "base.html" %}

{% block content %}

<h1>您好 <span class="text-primary">{{ user.username }}</span></h1>

<hr>

<img src="{{ user.avatar }}" width="100px">
<hr>

<div><strong>性别</strong>:
    {% if user.gender == 'male' %}
    小哥哥
    {% elif user.gender == 'female' %}
    小姐姐
    {% else %}
    保密
    {% endif %}
</div>
<hr>

<div><strong>生日</strong>: {{ user.birthday }}</div>
<hr>

<div><strong>常居地</strong>: {{ user.location }}</div>
<hr>

<div><strong>个人简介</strong>: {{ user.bio }}</div>
<hr>

<div><strong>注册时间</strong>: {{ user.created }}</div>
<hr>

<a class="btn btn-success" href="/user/update">修改个人资料</a>
{% endblock %}

App/templates/login.html
{% extends "base.html" %}

{% block content %}

<h1>欢迎登录</h1>

<hr>

{% if err %}
<div class="alert alert-danger" role="alert">
    {{ err }}
</div>
{% endif %}

<form action="{{ url_for('blue.login') }}" method="POST">
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">昵称</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" placeholder="请输入昵称" name="username">
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">密码</label>
        <div class="col-sm-6">
            <input type="password" class="form-control" placeholder="请输入密码" name="password">
        </div>
    </div>

    <button type="submit" class="btn btn-primary offset-md-2">提交</button>
</form>

{% endblock %}

App/templates/register.html
{% extends 'base.html' %}

{% block content %}

<h1>欢迎注册</h1>

<hr>

{% if err %}
<div class="alert alert-danger" role="alert">
    {{ err }}
</div>
{% endif %}

<form action="{{ url_for('blue.register') }}" method="POST">
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">昵称</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" placeholder="请输入昵称" name="username">
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">密码</label>
        <div class="col-sm-6">
            <input type="password" class="form-control" placeholder="请输入密码" name="password">
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">性别</label>
        <div class="col-sm-6">
            <select class="custom-select" name="gender">
                <option value="unknown" selected>保密</option>
                <option value="male">小哥哥</option>
                <option value="female">小姐姐</option>
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">生日</label>
        <div class="col-sm-6">
            <input type="date" class="form-control" name="birthday">
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">常居地</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" placeholder="请输入您的所在的地区" name="location">
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">个人简介</label>
        <div class="col-sm-6">
            <textarea class="form-control" placeholder="请输入个人简介" name="bio" rows="5"></textarea>
        </div>
    </div>

    <button type="submit" class="btn btn-primary offset-md-2">提交</button>
</form>

{% endblock %}

App/templates/sendWeibo.html
{% extends 'base.html' %}

{% block content %}
    <form action="{{ url_for('blue.sendWeibo') }}" method="POST">
    标题：<input type="text" name="title">
    <hr>

    正文：
    <br>
    <textarea name="content" rows="20" cols="80"></textarea>
    <br>

    <input type="submit" value="提交">
    </form>
{% endblock %}

App/templates/show_weibo.html
{% extends "base.html" %}


{% block content %}

<h1>微博</h1>
<hr>
<ul>
    {% for weibo in all_weibo %}
    <li><a href="/weibo/read?weibo_id={{ weibo.id }}">{{ weibo.topic }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

App/templates/update.html
{% extends "base.html" %}

{% block content %}

<h1>修改个人信息</h1>

<hr>

{% if err %}
<div class="alert alert-danger" role="alert">
    {{ err }}
</div>
{% endif %}

<form action="/user/update" method="POST" enctype="multipart/form-data">
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">昵称</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" placeholder="请输入昵称" name="username" value="{{ user.username }}">
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">性别</label>
        <div class="col-sm-6">
            <select class="custom-select" name="gender">
                <option value="unknow" {% if user.gender == 'unknow' %}selected{% endif %}>保密</option>
                <option value="male" {% if user.gender == 'male' %}selected{% endif %}>小哥哥</option>
                <option value="female" {% if user.gender == 'female' %}selected{% endif %}>小姐姐</option>
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">生日</label>
        <div class="col-sm-6">
            <input type="date" class="form-control" name="birthday" value="{{ user.birthday }}">
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">常居地</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" placeholder="请输入您的所在的地区" name="location" value="{{ user.location }}">
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">个人简介</label>
        <div class="col-sm-6">
            <textarea class="form-control" placeholder="请输入个人简介" name="bio" rows="5">{{ user.bio }}</textarea>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">头像</label>
        <div class="col-sm-6">
            <input type="file" class="form-control-file" accept="image/*" name="avatar">
        </div>
    </div>

    <button type="submit" class="btn btn-primary offset-md-2">提交</button>
</form>

{% endblock %}